### PR TITLE
Pull request to merge Julia integration with somoclu

### PR DESCRIPTION
**Pull request by sambitdash**

### CODE REVIEW

**Comment by sambitdash** [comment]
Can you revert the pull request? I need to rebase to one chunk before final commit. I thought you may have concerns on a few of the checkins so left out the detailed check-ins. Some of the intermediate codes are highly experimental need not be there in the final code repo.

**Comment by peterwittek** [comment]
I can't revert it: I started some clean-up in the meantime, particularly related to issue #103. I reviewed the changes everywhere outside `julia.cpp`, and I was happy with them, hence the merge.

Is there any particular bit of code that you find problematic? If it is all in `julia.cpp`, just send a new PR please. I will not get to the Julia part in a few hours.

**Comment by sambitdash** [comment]
No problems. Developers tend to check-in lots of intermediate junk code into their private branches and when they merge to the main line, it's expected that the mainline should not unnecessarily have those intermediate code. It should be like one PR and one check-in and one feature. I did not rebase squash before the check-in thinking you will have review comments and I may have to revert intermediate check-ins. But now that the code in subsequent check-ins will not change anything.

**Comment by peterwittek** [comment]
Yeah, I was sloppy with this one. Sorry about it.

**Comment by peterwittek** [comment]
I finished making small revisions in the code. You will hate me for this, but maybe we can compile the Julia part as part of the `lib` target. There's more boilerplate code there for the other interfaces, so no harm would be done.

Whenever we finish this new Julia interface, Somoclu will be ripe for a new release.

Thanks for the help so far. At the end of it, I might actually learn some C++.

**Comment by sambitdash** [comment]
I always love my code being re-edited for the better. So no harms done. Please go ahead with any changes which may benefit the code base. But, at some point feel a bit guilty of making you work at odd hours :-(.

**Pull request merged**
